# Generated by Django 5.1.7 on 2025-08-18 13:15

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_cataloguepage_realisationpage_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Texte d’intro au-dessus des infos.')),
                ('adresse', wagtail.fields.RichTextField(blank=True, help_text='Adresse postale (peut contenir <br>).')),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('map_query', models.CharField(blank=True, help_text="Ex: 'Atelier Dupont Saguenay' ou '48.416, -71.065'", max_length=255)),
                ('map_zoom', models.PositiveIntegerField(default=14, help_text='Niveau de zoom 1–20')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.DeleteModel(
            name='PageContact',
        ),
    ]
