# Generated by Django 5.1.7 on 2025-08-18 13:42

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_contactpage_delete_pagecontact'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevisPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Texte d’introduction au-dessus du formulaire')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='pagedevis',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='ChampFormulaire',
        ),
        migrations.DeleteModel(
            name='PageDevis',
        ),
    ]
