# Generated by Django 5.1.7 on 2025-08-24 23:20

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_devispage_remove_pagedevis_page_ptr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cataloguepage',
            name='contenu',
            field=wagtail.fields.StreamField([('item', 4)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 3: ('wagtail.blocks.DecimalBlock', (), {'decimal_places': 2, 'help_text': 'Prix (optionnel)', 'max_digits': 10, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 0), ('titre', 1), ('details', 2), ('prix', 3)]], {})}),
        ),
    ]
